/**
 * Unity Moderation Events API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: alpha-1.0
 * Contact: mp-suite-player-safety@unity3d.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace VivoxModeration
{

/*
 * OpenAPIModelVivoxChannelRequest
 *
 * 
 */
class VIVOXMODERATION_API OpenAPIModelVivoxChannelRequest : public Model
{
public:
    virtual ~OpenAPIModelVivoxChannelRequest() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* The name of the Vivox channel */
	TOptional<FString> Name;
	/* The URI of the Vivox channel */
	TOptional<FString> Uri;
};

}
