/**
 * Unity Moderation Events API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: alpha-1.0
 * Contact: mp-suite-player-safety@unity3d.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace VivoxModeration
{

/*
 * OpenAPIErrorsErrorResponseBody
 *
 * 
 */
class VIVOXMODERATION_API OpenAPIErrorsErrorResponseBody : public Model
{
public:
    virtual ~OpenAPIErrorsErrorResponseBody() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<int32> Code;
	TOptional<FString> Detail;
	TOptional<FString> Instance;
	TOptional<int32> Status;
	TOptional<FString> Title;
	TOptional<FString> Type;
};

}
