/**
 * Unity Moderation Events API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: alpha-1.0
 * Contact: mp-suite-player-safety@unity3d.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "VivoxModerationModule.h"

IMPLEMENT_MODULE(FVivoxModerationModule, VivoxModeration);
DEFINE_LOG_CATEGORY(LogModeration)

void FVivoxModerationModule::StartupModule()
{
}

void FVivoxModerationModule::ShutdownModule()
{
}
